name: Build and Push All Services
on:
  push:
    branches:
      - main
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - config-server
          - gateway-service
          - user-service
          - auth-service
          - analytics-service
          - discovery-service
          - cart-service
          - notification-service
          - order-service
          - payment-service
          - product-service
          - review-service
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build JAR with Maven
        run: mvn clean package -pl services/${{ matrix.service }} -am -DskipTests
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: services/${{ matrix.service }}
          push: true
          tags: lehonganh0201/${{ matrix.service }}:latest